services:
  stan-app:
    image: stan-app:latest
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"

    command: sleep infinity

    volumes:
      # The workspace directory
      - ./:/workspace:cached

    environment:
      - MONGO_URL=mongodb://mongo:27017

    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  logs-data:
